print("Diga o seu nome: ")
Nome = str(input())
print("Diga o seu apelido: ")
Apelido = str(input())
print("Diga o seu modulo")
Modulo = str(input())
print("Diga o ano: ")
Ano = int(input())
print(f'{Apelido}, {None} ({Ano}) {Modulo}')